CREATE TABLE tribunales (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre      VARCHAR(300) NOT NULL,
  region      VARCHAR(100) NOT NULL,
  activo      BOOLEAN      NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_tribunales_region ON tribunales (region);

INSERT INTO tribunales (nombre, region) VALUES
-- Arica y Parinacota
('1° Juzgado de Policía Local de Arica',          'Arica y Parinacota'),
('2° Juzgado de Policía Local de Arica',          'Arica y Parinacota'),
('Juzgado de Policía Local de Camarones',         'Arica y Parinacota'),
('Juzgado de Policía Local de General Lagos',     'Arica y Parinacota'),
('Juzgado de Policía Local de Putre',             'Arica y Parinacota'),

-- Tarapacá
('1° Juzgado de Policía Local de Iquique',        'Tarapacá'),
('2° Juzgado de Policía Local de Iquique',        'Tarapacá'),
('Juzgado de Policía Local de Alto Hospicio',     'Tarapacá'),
('Juzgado de Policía Local de Camiña',            'Tarapacá'),
('Juzgado de Policía Local de Colchane',          'Tarapacá'),
('Juzgado de Policía Local de Huara',             'Tarapacá'),
('Juzgado de Policía Local de Pica',              'Tarapacá'),
('Juzgado de Policía Local de Pozo Almonte',      'Tarapacá'),

-- Antofagasta
('1° Juzgado de Policía Local de Antofagasta',    'Antofagasta'),
('2° Juzgado de Policía Local de Antofagasta',    'Antofagasta'),
('3° Juzgado de Policía Local de Antofagasta',    'Antofagasta'),
('1° Juzgado de Policía Local de Calama',         'Antofagasta'),
('2° Juzgado de Policía Local de Calama',         'Antofagasta'),
('Juzgado de Policía Local de María Elena',       'Antofagasta'),
('Juzgado de Policía Local de Mejillones',        'Antofagasta'),
('Juzgado de Policía Local de Ollagüe',           'Antofagasta'),
('Juzgado de Policía Local de San Pedro de Atacama', 'Antofagasta'),
('Juzgado de Policía Local de Sierra Gorda',      'Antofagasta'),
('Juzgado de Policía Local de Taltal',            'Antofagasta'),
('Juzgado de Policía Local de Tocopilla',         'Antofagasta'),

-- Atacama
('1° Juzgado de Policía Local de Copiapó',        'Atacama'),
('2° Juzgado de Policía Local de Copiapó',        'Atacama'),
('Juzgado de Policía Local de Alto del Carmen',   'Atacama'),
('Juzgado de Policía Local de Caldera',           'Atacama'),
('Juzgado de Policía Local de Chañaral',          'Atacama'),
('Juzgado de Policía Local de Diego de Almagro',  'Atacama'),
('Juzgado de Policía Local de Freirina',          'Atacama'),
('Juzgado de Policía Local de Huasco',            'Atacama'),
('Juzgado de Policía Local de Tierra Amarilla',   'Atacama'),
('Juzgado de Policía Local de Vallenar',          'Atacama'),

-- Coquimbo
('1° Juzgado de Policía Local de La Serena',      'Coquimbo'),
('2° Juzgado de Policía Local de La Serena',      'Coquimbo'),
('1° Juzgado de Policía Local de Ovalle',         'Coquimbo'),
('2° Juzgado de Policía Local de Ovalle',         'Coquimbo'),
('Juzgado de Policía Local de Andacollo',         'Coquimbo'),
('Juzgado de Policía Local de Canela',            'Coquimbo'),
('Juzgado de Policía Local de Combarbalá',        'Coquimbo'),
('Juzgado de Policía Local de Coquimbo',          'Coquimbo'),
('Juzgado de Policía Local de Illapel',           'Coquimbo'),
('Juzgado de Policía Local de La Higuera',        'Coquimbo'),
('Juzgado de Policía Local de Los Vilos',         'Coquimbo'),
('Juzgado de Policía Local de Monte Patria',      'Coquimbo'),
('Juzgado de Policía Local de Paihuano',          'Coquimbo'),
('Juzgado de Policía Local de Punitaqui',         'Coquimbo'),
('Juzgado de Policía Local de Río Hurtado',       'Coquimbo'),
('Juzgado de Policía Local de Salamanca',         'Coquimbo'),
('Juzgado de Policía Local de Vicuña',            'Coquimbo'),

-- Valparaíso
('1° Juzgado de Policía Local de Valparaíso',     'Valparaíso'),
('2° Juzgado de Policía Local de Valparaíso',     'Valparaíso'),
('3° Juzgado de Policía Local de Valparaíso',     'Valparaíso'),
('1° Juzgado de Policía Local de Viña del Mar',   'Valparaíso'),
('2° Juzgado de Policía Local de Viña del Mar',   'Valparaíso'),
('3° Juzgado de Policía Local de Viña del Mar',   'Valparaíso'),
('1° Juzgado de Policía Local de Los Andes',      'Valparaíso'),
('2° Juzgado de Policía Local de Los Andes',      'Valparaíso'),
('1° Juzgado de Policía Local de San Antonio',    'Valparaíso'),
('2° Juzgado de Policía Local de San Antonio',    'Valparaíso'),
('1° Juzgado de Policía Local de San Felipe',     'Valparaíso'),
('2° Juzgado de Policía Local de San Felipe',     'Valparaíso'),
('Juzgado de Policía Local de Algarrobo',         'Valparaíso'),
('Juzgado de Policía Local de Cabildo',           'Valparaíso'),
('Juzgado de Policía Local de Calle Larga',       'Valparaíso'),
('Juzgado de Policía Local de Cartagena',         'Valparaíso'),
('Juzgado de Policía Local de Casablanca',        'Valparaíso'),
('Juzgado de Policía Local de Concón',            'Valparaíso'),
('Juzgado de Policía Local de El Quisco',         'Valparaíso'),
('Juzgado de Policía Local de El Tabo',           'Valparaíso'),
('Juzgado de Policía Local de Hijuelas',          'Valparaíso'),
('Juzgado de Policía Local de Isla de Pascua',    'Valparaíso'),
('Juzgado de Policía Local de Juan Fernández',    'Valparaíso'),
('Juzgado de Policía Local de La Calera',         'Valparaíso'),
('Juzgado de Policía Local de La Cruz',           'Valparaíso'),
('Juzgado de Policía Local de La Ligua',          'Valparaíso'),
('Juzgado de Policía Local de Limache',           'Valparaíso'),
('Juzgado de Policía Local de Nogales',           'Valparaíso'),
('Juzgado de Policía Local de Olmué',             'Valparaíso'),
('Juzgado de Policía Local de Panquehue',         'Valparaíso'),
('Juzgado de Policía Local de Papudo',            'Valparaíso'),
('Juzgado de Policía Local de Petorca',           'Valparaíso'),
('Juzgado de Policía Local de Putaendo',          'Valparaíso'),
('Juzgado de Policía Local de Quillota',          'Valparaíso'),
('Juzgado de Policía Local de Quintero',          'Valparaíso'),
('Juzgado de Policía Local de Rinconada',         'Valparaíso'),
('Juzgado de Policía Local de San Esteban',       'Valparaíso'),
('Juzgado de Policía Local de Santa María',       'Valparaíso'),
('Juzgado de Policía Local de Santo Domingo',     'Valparaíso'),
('Juzgado de Policía Local de Villa Alemana',     'Valparaíso'),
('Juzgado de Policía Local de Zapallar',          'Valparaíso'),

-- Metropolitana
('1° Juzgado de Policía Local de Santiago',       'Metropolitana'),
('2° Juzgado de Policía Local de Santiago',       'Metropolitana'),
('3° Juzgado de Policía Local de Santiago',       'Metropolitana'),
('4° Juzgado de Policía Local de Santiago',       'Metropolitana'),
('1° Juzgado de Policía Local de Maipú',          'Metropolitana'),
('2° Juzgado de Policía Local de Maipú',          'Metropolitana'),
('3° Juzgado de Policía Local de Maipú',          'Metropolitana'),
('1° Juzgado de Policía Local de Puente Alto',    'Metropolitana'),
('2° Juzgado de Policía Local de Puente Alto',    'Metropolitana'),
('1° Juzgado de Policía Local de El Bosque',      'Metropolitana'),
('2° Juzgado de Policía Local de El Bosque',      'Metropolitana'),
('1° Juzgado de Policía Local de La Florida',     'Metropolitana'),
('2° Juzgado de Policía Local de La Florida',     'Metropolitana'),
('1° Juzgado de Policía Local de Las Condes',     'Metropolitana'),
('2° Juzgado de Policía Local de Las Condes',     'Metropolitana'),
('1° Juzgado de Policía Local de Providencia',    'Metropolitana'),
('2° Juzgado de Policía Local de Providencia',    'Metropolitana'),
('1° Juzgado de Policía Local de San Bernardo',   'Metropolitana'),
('2° Juzgado de Policía Local de San Bernardo',   'Metropolitana'),
('1° Juzgado de Policía Local de San Miguel',     'Metropolitana'),
('2° Juzgado de Policía Local de San Miguel',     'Metropolitana'),
('Juzgado de Policía Local de Alhué',             'Metropolitana'),
('Juzgado de Policía Local de Buin',              'Metropolitana'),
('Juzgado de Policía Local de Calera de Tango',   'Metropolitana'),
('Juzgado de Policía Local de Cerrillos',         'Metropolitana'),
('Juzgado de Policía Local de Cerro Navia',       'Metropolitana'),
('Juzgado de Policía Local de Colina',            'Metropolitana'),
('Juzgado de Policía Local de Conchalí',          'Metropolitana'),
('Juzgado de Policía Local de Curacaví',          'Metropolitana'),
('Juzgado de Policía Local de El Monte',          'Metropolitana'),
('Juzgado de Policía Local de Estación Central',  'Metropolitana'),
('Juzgado de Policía Local de Huechuraba',        'Metropolitana'),
('Juzgado de Policía Local de Independencia',     'Metropolitana'),
('Juzgado de Policía Local de Isla de Maipo',     'Metropolitana'),
('Juzgado de Policía Local de La Cisterna',       'Metropolitana'),
('Juzgado de Policía Local de La Granja',         'Metropolitana'),
('Juzgado de Policía Local de La Pintana',        'Metropolitana'),
('Juzgado de Policía Local de La Reina',          'Metropolitana'),
('Juzgado de Policía Local de Lampa',             'Metropolitana'),
('Juzgado de Policía Local de Lo Barnechea',      'Metropolitana'),
('Juzgado de Policía Local de Lo Espejo',         'Metropolitana'),
('Juzgado de Policía Local de Lo Prado',          'Metropolitana'),
('Juzgado de Policía Local de Macul',             'Metropolitana'),
('Juzgado de Policía Local de María Pinto',       'Metropolitana'),
('Juzgado de Policía Local de Melipilla',         'Metropolitana'),
('Juzgado de Policía Local de Ñuñoa',             'Metropolitana'),
('Juzgado de Policía Local de Padre Hurtado',     'Metropolitana'),
('Juzgado de Policía Local de Paine',             'Metropolitana'),
('Juzgado de Policía Local de Pedro Aguirre Cerda', 'Metropolitana'),
('Juzgado de Policía Local de Peñaflor',          'Metropolitana'),
('Juzgado de Policía Local de Peñalolén',         'Metropolitana'),
('Juzgado de Policía Local de Pirque',            'Metropolitana'),
('Juzgado de Policía Local de Pudahuel',          'Metropolitana'),
('Juzgado de Policía Local de Quilicura',         'Metropolitana'),
('Juzgado de Policía Local de Quinta Normal',     'Metropolitana'),
('Juzgado de Policía Local de Recoleta',          'Metropolitana'),
('Juzgado de Policía Local de Renca',             'Metropolitana'),
('Juzgado de Policía Local de San Joaquín',       'Metropolitana'),
('Juzgado de Policía Local de San José de Maipo', 'Metropolitana'),
('Juzgado de Policía Local de San Pedro',         'Metropolitana'),
('Juzgado de Policía Local de San Ramón',         'Metropolitana'),
('Juzgado de Policía Local de Talagante',         'Metropolitana'),
('Juzgado de Policía Local de Tiltil',            'Metropolitana'),
('Juzgado de Policía Local de Vitacura',          'Metropolitana'),

-- O'Higgins
('1° Juzgado de Policía Local de Rancagua',          'O''Higgins'),
('2° Juzgado de Policía Local de Rancagua',          'O''Higgins'),
('Juzgado de Policía Local de Chépica',              'O''Higgins'),
('Juzgado de Policía Local de Chimbarongo',          'O''Higgins'),
('Juzgado de Policía Local de Codegua',              'O''Higgins'),
('Juzgado de Policía Local de Coinco',               'O''Higgins'),
('Juzgado de Policía Local de Coltauco',             'O''Higgins'),
('Juzgado de Policía Local de Doñihue',              'O''Higgins'),
('Juzgado de Policía Local de Graneros',             'O''Higgins'),
('Juzgado de Policía Local de La Estrella',          'O''Higgins'),
('Juzgado de Policía Local de Las Cabras',           'O''Higgins'),
('Juzgado de Policía Local de Litueche',             'O''Higgins'),
('Juzgado de Policía Local de Lolol',                'O''Higgins'),
('Juzgado de Policía Local de Machalí',              'O''Higgins'),
('Juzgado de Policía Local de Malloa',               'O''Higgins'),
('Juzgado de Policía Local de Marchigüe',            'O''Higgins'),
('Juzgado de Policía Local de Mostazal',             'O''Higgins'),
('Juzgado de Policía Local de Nancagua',             'O''Higgins'),
('Juzgado de Policía Local de Navidad',              'O''Higgins'),
('Juzgado de Policía Local de Olivar',               'O''Higgins'),
('Juzgado de Policía Local de Palmilla',             'O''Higgins'),
('Juzgado de Policía Local de Paredones',            'O''Higgins'),
('Juzgado de Policía Local de Peralillo',            'O''Higgins'),
('Juzgado de Policía Local de Peumo',                'O''Higgins'),
('Juzgado de Policía Local de Pichidegua',           'O''Higgins'),
('Juzgado de Policía Local de Pichilemu',            'O''Higgins'),
('Juzgado de Policía Local de Placilla',             'O''Higgins'),
('Juzgado de Policía Local de Pumanque',             'O''Higgins'),
('Juzgado de Policía Local de Quinta de Tilcoco',    'O''Higgins'),
('Juzgado de Policía Local de Rengo',                'O''Higgins'),
('Juzgado de Policía Local de Requínoa',             'O''Higgins'),
('Juzgado de Policía Local de San Fernando',         'O''Higgins'),
('Juzgado de Policía Local de San Vicente de Tagua Tagua', 'O''Higgins'),
('Juzgado de Policía Local de Santa Cruz',           'O''Higgins'),

-- Maule
('1° Juzgado de Policía Local de Talca',          'Maule'),
('2° Juzgado de Policía Local de Talca',          'Maule'),
('1° Juzgado de Policía Local de Curicó',         'Maule'),
('2° Juzgado de Policía Local de Curicó',         'Maule'),
('Juzgado de Policía Local de Cauquenes',         'Maule'),
('Juzgado de Policía Local de Chanco',            'Maule'),
('Juzgado de Policía Local de Colbún',            'Maule'),
('Juzgado de Policía Local de Constitución',      'Maule'),
('Juzgado de Policía Local de Curepto',           'Maule'),
('Juzgado de Policía Local de Empedrado',         'Maule'),
('Juzgado de Policía Local de Hualañé',           'Maule'),
('Juzgado de Policía Local de Licantén',          'Maule'),
('Juzgado de Policía Local de Linares',           'Maule'),
('Juzgado de Policía Local de Longaví',           'Maule'),
('Juzgado de Policía Local de Maule',             'Maule'),
('Juzgado de Policía Local de Molina',            'Maule'),
('Juzgado de Policía Local de Parral',            'Maule'),
('Juzgado de Policía Local de Pelarco',           'Maule'),
('Juzgado de Policía Local de Pelluhue',          'Maule'),
('Juzgado de Policía Local de Pencahue',          'Maule'),
('Juzgado de Policía Local de Rauco',             'Maule'),
('Juzgado de Policía Local de Retiro',            'Maule'),
('Juzgado de Policía Local de Río Claro',         'Maule'),
('Juzgado de Policía Local de Romeral',           'Maule'),
('Juzgado de Policía Local de Sagrada Familia',   'Maule'),
('Juzgado de Policía Local de San Clemente',      'Maule'),
('Juzgado de Policía Local de San Javier',        'Maule'),
('Juzgado de Policía Local de San Rafael',        'Maule'),
('Juzgado de Policía Local de Teno',              'Maule'),
('Juzgado de Policía Local de Vichuquén',         'Maule'),
('Juzgado de Policía Local de Villa Alegre',      'Maule'),
('Juzgado de Policía Local de Yerbas Buenas',     'Maule'),

-- Ñuble
('1° Juzgado de Policía Local de Chillán',        'Ñuble'),
('2° Juzgado de Policía Local de Chillán',        'Ñuble'),
('Juzgado de Policía Local de Bulnes',            'Ñuble'),
('Juzgado de Policía Local de Chillán Viejo',     'Ñuble'),
('Juzgado de Policía Local de Cobquecura',        'Ñuble'),
('Juzgado de Policía Local de Coelemu',           'Ñuble'),
('Juzgado de Policía Local de Coihueco',          'Ñuble'),
('Juzgado de Policía Local de El Carmen',         'Ñuble'),
('Juzgado de Policía Local de Ninhue',            'Ñuble'),
('Juzgado de Policía Local de Ñiquén',            'Ñuble'),
('Juzgado de Policía Local de Pemuco',            'Ñuble'),
('Juzgado de Policía Local de Pinto',             'Ñuble'),
('Juzgado de Policía Local de Portezuelo',        'Ñuble'),
('Juzgado de Policía Local de Quillón',           'Ñuble'),
('Juzgado de Policía Local de Quirihue',          'Ñuble'),
('Juzgado de Policía Local de Ranquil',           'Ñuble'),
('Juzgado de Policía Local de San Carlos',        'Ñuble'),
('Juzgado de Policía Local de San Fabián de Alico', 'Ñuble'),
('Juzgado de Policía Local de San Ignacio',       'Ñuble'),
('Juzgado de Policía Local de San Nicolás',       'Ñuble'),
('Juzgado de Policía Local de Trehuaco',          'Ñuble'),
('Juzgado de Policía Local de Yungay',            'Ñuble'),

-- Biobío
('1° Juzgado de Policía Local de Concepción',     'Biobío'),
('2° Juzgado de Policía Local de Concepción',     'Biobío'),
('3° Juzgado de Policía Local de Concepción',     'Biobío'),
('1° Juzgado de Policía Local de Los Ángeles',    'Biobío'),
('2° Juzgado de Policía Local de Los Ángeles',    'Biobío'),
('Juzgado de Policía Local de Alto Biobío',       'Biobío'),
('Juzgado de Policía Local de Antuco',            'Biobío'),
('Juzgado de Policía Local de Arauco',            'Biobío'),
('Juzgado de Policía Local de Cabrero',           'Biobío'),
('Juzgado de Policía Local de Cañete',            'Biobío'),
('Juzgado de Policía Local de Chiguayante',       'Biobío'),
('Juzgado de Policía Local de Contulmo',          'Biobío'),
('Juzgado de Policía Local de Coronel',           'Biobío'),
('Juzgado de Policía Local de Curanilahue',       'Biobío'),
('Juzgado de Policía Local de Florida',           'Biobío'),
('Juzgado de Policía Local de Hualpén',           'Biobío'),
('Juzgado de Policía Local de Hualqui',           'Biobío'),
('Juzgado de Policía Local de Laja',              'Biobío'),
('Juzgado de Policía Local de Lebu',              'Biobío'),
('Juzgado de Policía Local de Los Álamos',        'Biobío'),
('Juzgado de Policía Local de Lota',              'Biobío'),
('Juzgado de Policía Local de Mulchén',           'Biobío'),
('Juzgado de Policía Local de Nacimiento',        'Biobío'),
('Juzgado de Policía Local de Negrete',           'Biobío'),
('Juzgado de Policía Local de Penco',             'Biobío'),
('Juzgado de Policía Local de Quilaco',           'Biobío'),
('Juzgado de Policía Local de Quilleco',          'Biobío'),
('Juzgado de Policía Local de San Pedro de la Paz', 'Biobío'),
('Juzgado de Policía Local de San Rosendo',       'Biobío'),
('Juzgado de Policía Local de Santa Bárbara',     'Biobío'),
('Juzgado de Policía Local de Santa Juana',       'Biobío'),
('Juzgado de Policía Local de Talcahuano',        'Biobío'),
('Juzgado de Policía Local de Tirúa',             'Biobío'),
('Juzgado de Policía Local de Tomé',              'Biobío'),
('Juzgado de Policía Local de Tucapel',           'Biobío'),
('Juzgado de Policía Local de Yumbel',            'Biobío'),

-- La Araucanía
('1° Juzgado de Policía Local de Temuco',         'La Araucanía'),
('2° Juzgado de Policía Local de Temuco',         'La Araucanía'),
('3° Juzgado de Policía Local de Temuco',         'La Araucanía'),
('Juzgado de Policía Local de Angol',             'La Araucanía'),
('Juzgado de Policía Local de Carahue',           'La Araucanía'),
('Juzgado de Policía Local de Collipulli',        'La Araucanía'),
('Juzgado de Policía Local de Cunco',             'La Araucanía'),
('Juzgado de Policía Local de Curacautín',        'La Araucanía'),
('Juzgado de Policía Local de Curarrehue',        'La Araucanía'),
('Juzgado de Policía Local de Ercilla',           'La Araucanía'),
('Juzgado de Policía Local de Freire',            'La Araucanía'),
('Juzgado de Policía Local de Galvarino',         'La Araucanía'),
('Juzgado de Policía Local de Gorbea',            'La Araucanía'),
('Juzgado de Policía Local de Lautaro',           'La Araucanía'),
('Juzgado de Policía Local de Loncoche',          'La Araucanía'),
('Juzgado de Policía Local de Lonquimay',         'La Araucanía'),
('Juzgado de Policía Local de Los Sauces',        'La Araucanía'),
('Juzgado de Policía Local de Lumaco',            'La Araucanía'),
('Juzgado de Policía Local de Melipeuco',         'La Araucanía'),
('Juzgado de Policía Local de Nueva Imperial',    'La Araucanía'),
('Juzgado de Policía Local de Padre Las Casas',   'La Araucanía'),
('Juzgado de Policía Local de Perquenco',         'La Araucanía'),
('Juzgado de Policía Local de Pitrufquén',        'La Araucanía'),
('Juzgado de Policía Local de Pucón',             'La Araucanía'),
('Juzgado de Policía Local de Purén',             'La Araucanía'),
('Juzgado de Policía Local de Renaico',           'La Araucanía'),
('Juzgado de Policía Local de Saavedra',          'La Araucanía'),
('Juzgado de Policía Local de Teodoro Schmidt',   'La Araucanía'),
('Juzgado de Policía Local de Toltén',            'La Araucanía'),
('Juzgado de Policía Local de Traiguén',          'La Araucanía'),
('Juzgado de Policía Local de Victoria',          'La Araucanía'),
('Juzgado de Policía Local de Vilcún',            'La Araucanía'),
('Juzgado de Policía Local de Villarrica',        'La Araucanía'),

-- Los Ríos
('1° Juzgado de Policía Local de Valdivia',       'Los Ríos'),
('2° Juzgado de Policía Local de Valdivia',       'Los Ríos'),
('Juzgado de Policía Local de Corral',            'Los Ríos'),
('Juzgado de Policía Local de Futrono',           'Los Ríos'),
('Juzgado de Policía Local de La Unión',          'Los Ríos'),
('Juzgado de Policía Local de Lago Ranco',        'Los Ríos'),
('Juzgado de Policía Local de Lanco',             'Los Ríos'),
('Juzgado de Policía Local de Los Lagos',         'Los Ríos'),
('Juzgado de Policía Local de Máfil',             'Los Ríos'),
('Juzgado de Policía Local de Mariquina',         'Los Ríos'),
('Juzgado de Policía Local de Paillaco',          'Los Ríos'),
('Juzgado de Policía Local de Panguipulli',       'Los Ríos'),
('Juzgado de Policía Local de Río Bueno',         'Los Ríos'),

-- Los Lagos
('1° Juzgado de Policía Local de Puerto Montt',   'Los Lagos'),
('2° Juzgado de Policía Local de Puerto Montt',   'Los Lagos'),
('1° Juzgado de Policía Local de Osorno',         'Los Lagos'),
('2° Juzgado de Policía Local de Osorno',         'Los Lagos'),
('Juzgado de Policía Local de Ancud',             'Los Lagos'),
('Juzgado de Policía Local de Calbuco',           'Los Lagos'),
('Juzgado de Policía Local de Castro',            'Los Lagos'),
('Juzgado de Policía Local de Chaitén',           'Los Lagos'),
('Juzgado de Policía Local de Chonchi',           'Los Lagos'),
('Juzgado de Policía Local de Cochamó',           'Los Lagos'),
('Juzgado de Policía Local de Curaco de Vélez',   'Los Lagos'),
('Juzgado de Policía Local de Dalcahue',          'Los Lagos'),
('Juzgado de Policía Local de Fresia',            'Los Lagos'),
('Juzgado de Policía Local de Frutillar',         'Los Lagos'),
('Juzgado de Policía Local de Futaleufú',         'Los Lagos'),
('Juzgado de Policía Local de Hualaihué',         'Los Lagos'),
('Juzgado de Policía Local de Llanquihue',        'Los Lagos'),
('Juzgado de Policía Local de Los Muermos',       'Los Lagos'),
('Juzgado de Policía Local de Maullín',           'Los Lagos'),
('Juzgado de Policía Local de Palena',            'Los Lagos'),
('Juzgado de Policía Local de Puerto Octay',      'Los Lagos'),
('Juzgado de Policía Local de Puerto Varas',      'Los Lagos'),
('Juzgado de Policía Local de Puqueldón',         'Los Lagos'),
('Juzgado de Policía Local de Queilén',           'Los Lagos'),
('Juzgado de Policía Local de Quellón',           'Los Lagos'),
('Juzgado de Policía Local de Quemchi',           'Los Lagos'),
('Juzgado de Policía Local de Quinchao',          'Los Lagos'),
('Juzgado de Policía Local de Río Negro',         'Los Lagos'),
('Juzgado de Policía Local de San Juan de la Costa', 'Los Lagos'),
('Juzgado de Policía Local de San Pablo',         'Los Lagos'),

-- Aysén
('Juzgado de Policía Local de Aysén',             'Aysén'),
('Juzgado de Policía Local de Chile Chico',       'Aysén'),
('Juzgado de Policía Local de Cisnes',            'Aysén'),
('Juzgado de Policía Local de Cochrane',          'Aysén'),
('Juzgado de Policía Local de Coyhaique',         'Aysén'),
('Juzgado de Policía Local de Guaitecas',         'Aysén'),
('Juzgado de Policía Local de Lago Verde',        'Aysén'),
('Juzgado de Policía Local de O''Higgins',        'Aysén'),
('Juzgado de Policía Local de Río Ibáñez',        'Aysén'),
('Juzgado de Policía Local de Tortel',            'Aysén'),

-- Magallanes
('Juzgado de Policía Local de Antártica',         'Magallanes'),
('Juzgado de Policía Local de Cabo de Hornos',    'Magallanes'),
('Juzgado de Policía Local de Laguna Blanca',     'Magallanes'),
('Juzgado de Policía Local de Natales',           'Magallanes'),
('Juzgado de Policía Local de Porvenir',          'Magallanes'),
('Juzgado de Policía Local de Primavera',         'Magallanes'),
('Juzgado de Policía Local de Punta Arenas',      'Magallanes'),
('Juzgado de Policía Local de Río Verde',         'Magallanes'),
('Juzgado de Policía Local de San Gregorio',      'Magallanes'),
('Juzgado de Policía Local de Timaukel',          'Magallanes'),
('Juzgado de Policía Local de Torres del Paine',  'Magallanes');
